<?php

namespace app\modules\v1\admin;

class Module extends \yii\base\Module
{
    public function init()
    {
        $this->modules = [
            "user" => user\Module::class,
            "brand" => brand\Module::class
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }
}