<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use yii\behaviors\TimestampBehavior;
use \app\models\CustomerQuery;

/**
 * This is the base-model class for table "customer".
 *
 * @property integer $id
 * @property string $name
 * @property string $code
 * @property string $phone
 * @property integer $gender
 * @property string $email
 * @property string $fb_url
 * @property string $thumbnail
 * @property string $city
 * @property string $district
 * @property string $ward
 * @property string $address
 * @property integer $group_customer
 * @property integer $type
 * @property string $tax_code
 * @property string $company_name
 * @property string $national
 * @property string $passport_number
 * @property string $bank_name
 * @property string $bank_account_number
 * @property double $current_debt
 * @property string $created_at
 * @property string $updated_at
 */
abstract class Customer extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'customer';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['timestamp'] = [
            'class' => TimestampBehavior::class,
            'value' => date("Y-m-d H:i:s"),
        ];

        return $behaviors;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['name', 'code', 'phone', 'gender', 'email', 'fb_url', 'thumbnail', 'city', 'district', 'ward', 'address', 'group_customer', 'type', 'tax_code', 'company_name', 'national', 'passport_number', 'bank_name', 'bank_account_number', 'current_debt'], 'default', 'value' => null],
            [['gender', 'group_customer', 'type'], 'integer'],
            [['current_debt'], 'number'],
            [['name', 'code', 'phone', 'email', 'thumbnail', 'city', 'district', 'ward', 'address', 'tax_code', 'company_name', 'national', 'passport_number', 'bank_name', 'bank_account_number'], 'string', 'max' => 255]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'name' => 'Name',
            'code' => 'Code',
            'phone' => 'Phone',
            'gender' => 'Gender',
            'email' => 'Email',
            'thumbnail' => 'Thumbnail',
            'city' => 'City',
            'district' => 'District',
            'ward' => 'Ward',
            'address' => 'Address',
            'group_customer' => 'Group Customer',
            'type' => 'Type',
            'tax_code' => 'Tax Code',
            'company_name' => 'Company Name',
            'national' => 'National',
            'passport_number' => 'Passport Number',
            'bank_name' => 'Bank Name',
            'bank_account_number' => 'Bank Account Number',
            'current_debt' => 'Current Debt',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ]);
    }

    /**
     * @inheritdoc
     * @return CustomerQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new CustomerQuery(static::class);
    }
}
