<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use yii\behaviors\TimestampBehavior;
use \app\models\EmployeeQuery;

/**
 * This is the base-model class for table "employee".
 *
 * @property integer $id
 * @property string $username
 * @property string $full_name
 * @property string $email
 * @property string $phone
 * @property string $position
 * @property string $thumbnail
 * @property string $address
 * @property integer $gender
 * @property string $birthday
 * @property string $start_date
 * @property integer $status
 * @property string $created_at
 * @property string $updated_at
 */
abstract class Employee extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'employee';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['timestamp'] = [
            'class' => TimestampBehavior::class,
            'value' => date("Y-m-d H:i:s"),
        ];

        return $behaviors;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['username', 'full_name', 'email', 'phone', 'position', 'thumbnail', 'address', 'gender', 'birthday', 'start_date', 'status'], 'default', 'value' => null],
            [['gender', 'status'], 'integer'],
            [['birthday', 'start_date'], 'safe'],
            [['username', 'full_name', 'email', 'phone', 'position', 'thumbnail', 'address'], 'string', 'max' => 255]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'username' => 'Username',
            'full_name' => 'Full Name',
            'email' => 'Email',
            'phone' => 'Phone',
            'position' => 'Position',
            'thumbnail' => 'Thumbnail',
            'address' => 'Address',
            'gender' => 'Gender',
            'birthday' => 'Birthday',
            'start_date' => 'Start Date',
            'status' => 'Status',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ]);
    }

    /**
     * @inheritdoc
     * @return EmployeeQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new EmployeeQuery(static::class);
    }
}
