<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use yii\behaviors\TimestampBehavior;
use \app\models\ItemAttributeValueQuery;

/**
 * This is the base-model class for table "item_variant_attribute".
 *
 * @property integer $id
 * @property integer $item_variant_id
 * @property integer $item_attribute_id
 * @property integer $item_attribute_value_id
 * @property string $created_at
 * @property string $updated_at
 */
abstract class ItemVariantAttribute extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'item_variant_attribute';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['timestamp'] = [
            'class' => TimestampBehavior::class,
            'value' => date("Y-m-d H:i:s"),
        ];

        return $behaviors;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['item_variant_id', 'item_attribute_id', 'item_attribute_value_id'], 'integer'],
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'item_variant_id' => 'Item Variant ID',
            'item_attribute_id' => 'Item Attribute ID',
            'item_attribute_value_id' => 'Item Attribute Value ID',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ]);
    }

    /**
     * @inheritdoc
     * @return ItemAttributeValueQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new ItemAttributeValueQuery(static::class);
    }
}
