<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use yii\behaviors\TimestampBehavior;
use \app\models\ItemVariantQuery;

/**
 * This is the base-model class for table "item_variant".
 *
 * @property integer $id
 * @property integer $item_id
 * @property string $name
 * @property string $thumbnail
 * @property string $sku
 * @property string $barcode
 * @property double $price
 * @property integer $stock
 * @property integer $status
 * @property string $created_at
 * @property string $updated_at
 */
abstract class ItemVariant extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'item_variant';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['timestamp'] = [
            'class' => TimestampBehavior::class,
            'value' => date("Y-m-d H:i:s"),
        ];

        return $behaviors;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['item_id', 'sku', 'barcode', 'price', 'stock', 'name', 'thumbnail', 'status'], 'default', 'value' => null],
            [['item_id', 'stock', 'status'], 'integer'],
            [['price'], 'number'],
            [['attributes'], 'safe'],
            [['name', 'thumbnail', 'sku', 'barcode'], 'string', 'max' => 255]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'item_id' => 'Item ID',
            'name' => 'Name',
            'thumbnail' => 'Thumbnail',
            'sku' => 'Sku',
            'barcode' => 'Barcode',
            'price' => 'Price',
            'stock' => 'Stock',
            'attributes' => 'Attributes',
            'status' => 'Status',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ]);
    }

    /**
     * @inheritdoc
     * @return ItemVariantQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new ItemVariantQuery(static::class);
    }
}
