<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use yii\behaviors\TimestampBehavior;
use \app\models\ItemQuery;

/**
 * This is the base-model class for table "item".
 *
 * @property integer $id
 * @property integer $category_id
 * @property integer $brand_id
 * @property string $name
 * @property string $slug
 * @property string $description
 * @property string $thumbnail
 * @property array $gallery
 * @property string $sku
 * @property double $price
 * @property double $cost
 * @property string $discount
 * @property integer $stock
 * @property string $weight
 * @property integer $status
 * @property string $created_at
 * @property string $updated_at
 */
abstract class Item extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'item';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['timestamp'] = [
            'class' => TimestampBehavior::class,
            'value' => date("Y-m-d H:i:s"),
        ];

        return $behaviors;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['category_id', 'brand_id', 'name', 'slug', 'description', 'thumbnail', 'gallery', 'sku', 'price', 'cost', 'discount', 'stock', 'weight', 'status'], 'default', 'value' => null],
            [['category_id', 'brand_id', 'stock', 'status'], 'integer'],
            [['gallery'], 'safe'],
            [['price', 'cost'], 'number'],
            [['name', 'slug', 'description', 'thumbnail', 'sku', 'discount', 'weight'], 'string', 'max' => 255]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'category_id' => 'Category ID',
            'brand_id' => 'Brand ID',
            'name' => 'Name',
            'slug' => 'Slug',
            'description' => 'Description',
            'thumbnail' => 'Thumbnail',
            'gallery' => 'Gallery',
            'sku' => 'Sku',
            'price' => 'Price',
            'cost' => 'Cost',
            'discount' => 'Discount',
            'stock' => 'Stock',
            'weight' => 'Weight',
            'status' => 'Status',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ]);
    }

    /**
     * @inheritdoc
     * @return ItemQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new ItemQuery(static::class);
    }
}
