<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use yii\behaviors\TimestampBehavior;
use \app\models\ItemAttributeValueQuery;

/**
 * This is the base-model class for table "item_attribute_value".
 *
 * @property integer $id
 * @property integer $attribute_id
 * @property string $value
 * @property integer $status
 * @property string $created_at
 * @property string $updated_at
 */
abstract class ItemAttributeValue extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'item_attribute_value';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['timestamp'] = [
            'class' => TimestampBehavior::class,
            'value' => date("Y-m-d H:i:s"),
        ];

        return $behaviors;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['attribute_id', 'value', 'status'], 'default', 'value' => null],
            [['attribute_id', 'status'], 'integer'],
            [['value'], 'string', 'max' => 255]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'attribute_id' => 'Attribute ID',
            'value' => 'Value',
            'status' => 'Status',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ]);
    }

    /**
     * @inheritdoc
     * @return ItemAttributeValueQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new ItemAttributeValueQuery(static::class);
    }
}
