<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use yii\behaviors\TimestampBehavior;
use \app\models\PaymentQuery;

/**
 * This is the base-model class for table "payment".
 *
 * @property integer $id
 * @property string $payment_no
 * @property string $date
 * @property string $payee_name
 * @property string $payee_phone
 * @property string $reason
 * @property double $amount
 * @property integer $payment_method
 * @property integer $invoice_id
 * @property integer $status
 * @property integer $created_by
 * @property string $created_at
 * @property string $updated_at
 */
abstract class Payment extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'payment';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['timestamp'] = [
            'class' => TimestampBehavior::class,
            'value' => date("Y-m-d H:i:s"),
        ];

        return $behaviors;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['payment_no', 'date', 'payee_name', 'payee_phone', 'reason', 'amount', 'payment_method', 'invoice_id', 'status'], 'default', 'value' => null],
            [['date'], 'safe'],
            [['reason'], 'string'],
            [['amount'], 'number'],
            [['payment_method', 'invoice_id', 'status'], 'integer'],
            [['payment_no', 'payee_name', 'payee_phone'], 'string', 'max' => 255]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'payment_no' => 'Payment No',
            'date' => 'Date',
            'payee_name' => 'Payee Name',
            'payee_phone' => 'Payee Phone',
            'reason' => 'Reason',
            'amount' => 'Amount',
            'payment_method' => 'Payment Method',
            'invoice_id' => 'Invoice ID',
            'created_by' => 'Created By',
            'status' => 'Status',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ]);
    }

    /**
     * @inheritdoc
     * @return PaymentQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new PaymentQuery(static::class);
    }
}
