<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use yii\behaviors\TimestampBehavior;
use \app\models\ReceiptQuery;

/**
 * This is the base-model class for table "receipt".
 *
 * @property integer $id
 * @property string $receipt_no
 * @property string $date
 * @property string $email
 * @property string $payer_name
 * @property string $payer_phone
 * @property string $reason
 * @property double $amount
 * @property integer $payment_method
 * @property integer $invoice_id
 * @property integer $start_date
 * @property integer $status
 * @property integer $created_by
 * @property string $created_at
 * @property string $updated_at
 */
abstract class Receipt extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'receipt';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['timestamp'] = [
            'class' => TimestampBehavior::class,
            'value' => date("Y-m-d H:i:s"),
        ];

        return $behaviors;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['receipt_no', 'date', 'email', 'payer_name', 'payer_phone', 'reason', 'amount', 'payment_method', 'invoice_id', 'start_date', 'status'], 'default', 'value' => null],
            [['date'], 'safe'],
            [['reason'], 'string'],
            [['amount'], 'number'],
            [['payment_method', 'invoice_id', 'start_date', 'status'], 'integer'],
            [['receipt_no', 'email', 'payer_name', 'payer_phone'], 'string', 'max' => 255]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'receipt_no' => 'Receipt No',
            'date' => 'Date',
            'email' => 'Email',
            'payer_name' => 'Payer Name',
            'payer_phone' => 'Payer Phone',
            'reason' => 'Reason',
            'amount' => 'Amount',
            'payment_method' => 'Payment Method',
            'invoice_id' => 'Invoice ID',
            'start_date' => 'Start Date',
            'created_by' => 'Created By',
            'status' => 'Status',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ]);
    }

    /**
     * @inheritdoc
     * @return ReceiptQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new ReceiptQuery(static::class);
    }
}
