<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use yii\behaviors\TimestampBehavior;
use \app\models\ShiftQuery;

/**
 * This is the base-model class for table "shift".
 *
 * @property integer $id
 * @property string $name
 * @property string $start_time
 * @property string $end_time
 * @property string $checkin_start
 * @property string $checkin_end
 * @property integer $duration
 * @property integer $status
 * @property string $created_at
 * @property string $updated_at
 */
abstract class Shift extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'shift';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['timestamp'] = [
            'class' => TimestampBehavior::class,
            'value' => (new \DateTime())->format('Y-m-d H:i:s'),
                        ];
        
    return $behaviors;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['name', 'start_time', 'end_time', 'checkin_start', 'checkin_end', 'duration', 'status'], 'default', 'value' => null],
            [['start_time', 'end_time', 'checkin_start', 'checkin_end'], 'safe'],
            [['duration', 'status'], 'integer'],
            [['name'], 'string', 'max' => 100]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'name' => 'Name',
            'start_time' => 'Start Time',
            'end_time' => 'End Time',
            'checkin_start' => 'Checkin Start',
            'checkin_end' => 'Checkin End',
            'duration' => 'Duration',
            'status' => 'Status',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ]);
    }

    /**
     * @inheritdoc
     * @return ShiftQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new ShiftQuery(static::class);
    }
}
