<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use yii\behaviors\TimestampBehavior;
use \app\models\StockInvoiceItemQuery;

/**
 * This is the base-model class for table "stock_invoice_item".
 *
 * @property integer $id
 * @property string $invoice_id
 * @property integer $product_id
 * @property integer $warehouse_id
 * @property integer $quantity
 * @property double $price
 * @property integer $total
 * @property string $created_at
 * @property string $updated_at
 */
abstract class StockInvoiceItem extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'stock_invoice_item';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['timestamp'] = [
            'class' => TimestampBehavior::class,
            'value' => date("Y-m-d H:i:s"),
        ];

        return $behaviors;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['invoice_id', 'product_id', 'warehouse_id', 'quantity', 'price', 'total'], 'default', 'value' => null],
            [['product_id', 'warehouse_id', 'quantity', 'total'], 'integer'],
            [['price'], 'number'],
            [['invoice_id'], 'string', 'max' => 255]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'invoice_id' => 'Invoice ID',
            'product_id' => 'Product ID',
            'warehouse_id' => 'Warehouse ID',
            'quantity' => 'Quantity',
            'price' => 'Price',
            'total' => 'Total',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ]);
    }

    /**
     * @inheritdoc
     * @return StockInvoiceItemQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new StockInvoiceItemQuery(static::class);
    }
}
