<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use yii\behaviors\TimestampBehavior;
use \app\models\StockInvoiceQuery;

/**
 * This is the base-model class for table "stock_invoice".
 *
 * @property integer $id
 * @property string $code
 * @property integer $type
 * @property integer $warehouse_id
 * @property integer $user_id
 * @property integer $vendor_id
 * @property string $note
 * @property integer $status
 * @property string $created_at
 * @property string $updated_at
 */
abstract class StockInvoice extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'stock_invoice';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['timestamp'] = [
            'class' => TimestampBehavior::class,
            'value' => date("Y-m-d H:i:s"),
        ];

        return $behaviors;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['code', 'type', 'warehouse_id', 'user_id', 'vendor_id','note', 'status'], 'default', 'value' => null],
            [['type', 'warehouse_id', 'user_id', 'vendor_id', 'status'], 'integer'],
            [['note'], 'string'],
            [['code'], 'string', 'max' => 255]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'code' => 'Code',
            'type' => 'Type',
            'warehouse_id' => 'Warehouse ID',
            'user_id' => 'User ID',
            'vendor_id' => 'Vendor ID',
            'note' => 'Note',
            'status' => 'Status',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ]);
    }

    /**
     * @inheritdoc
     * @return StockInvoiceQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new StockInvoiceQuery(static::class);
    }
}
