<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use yii\behaviors\TimestampBehavior;
use \app\models\StockCheckItemQuery;

/**
 * This is the base-model class for table "stock_check_item".
 *
 * @property integer $id
 * @property string $check_id
 * @property integer $product_variant_id
 * @property integer $actual_quantity
 * @property integer $system_quantity
 * @property integer $difference_quantity
 * @property string $note
 * @property string $created_at
 * @property string $updated_at
 */
abstract class StockCheckItem extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'stock_check_item';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['timestamp'] = [
            'class' => TimestampBehavior::class,
            'value' => date("Y-m-d H:i:s"),
        ];

        return $behaviors;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['check_id', 'product_variant_id', 'actual_quantity', 'system_quantity', 'difference_quantity', 'note'], 'default', 'value' => null],
            [['product_variant_id', 'actual_quantity', 'system_quantity', 'difference_quantity'], 'integer'],
            [['check_id', 'note'], 'string', 'max' => 255]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'check_id' => 'Check ID',
            'product_variant_id' => 'Product Variant ID',
            'actual_quantity' => 'Actual Quantity',
            'system_quantity' => 'System Quantity',
            'difference_quantity' => 'Difference Quantity',
            'note' => 'Note',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ]);
    }

    /**
     * @inheritdoc
     * @return StockCheckItemQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new StockCheckItemQuery(static::class);
    }
}
