<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use yii\behaviors\TimestampBehavior;
use \app\models\UserQuery;

/**
 * This is the base-model class for table "user".
 *
 * @property integer $id
 * @property string $access_token
 * @property string $token
 * @property string $auth_key
 * @property string $email
 * @property string $username
 * @property string $phone
 * @property string $oauth_client
 * @property string $oauth_client_user_id
 * @property integer $status
 * @property integer $is_verify
 * @property string $password_hash
 * @property string $logged_at
 * @property string $created_at
 * @property string $updated_at
 */
abstract class User extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'user';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['timestamp'] = [
            'class' => TimestampBehavior::class,
            'value' => date("Y-m-d H:i:s"),
        ];

        return $behaviors;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['access_token', 'token', 'auth_key', 'email', 'username', 'phone', 'oauth_client', 'oauth_client_user_id', 'status', 'password_hash', 'logged_at'], 'default', 'value' => null],
            [['is_verify'], 'default', 'value' => 0],
            [['status', 'is_verify'], 'integer'],
            [['logged_at'], 'safe'],
            [['access_token', 'token', 'auth_key', 'email', 'username', 'phone', 'oauth_client', 'oauth_client_user_id', 'password_hash'], 'string', 'max' => 255]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'access_token' => 'Access Token',
            'token' => 'Token',
            'auth_key' => 'Auth Key',
            'email' => 'Email',
            'username' => 'Username',
            'phone' => 'Phone',
            'oauth_client' => 'Oauth Client',
            'oauth_client_user_id' => 'Oauth Client User ID',
            'status' => 'Status',
            'is_verify' => 'Is Verify',
            'password_hash' => 'Password Hash',
            'logged_at' => 'Logged At',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ]);
    }

    /**
     * @inheritdoc
     * @return UserQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new UserQuery(static::class);
    }
}
