<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use yii\behaviors\TimestampBehavior;
use \app\models\VendorQuery;

/**
 * This is the base-model class for table "vendor".
 *
 * @property integer $id
 * @property string $name
 * @property string $code
 * @property string $phone
 * @property string $email
 * @property string $city
 * @property string $district
 * @property string $ward
 * @property string $address
 * @property integer $group_vendor
 * @property integer $type
 * @property string $tax_code
 * @property string $company_name
 * @property double $current_debt
 * @property string $created_at
 * @property string $updated_at
 */
abstract class Vendor extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'vendor';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['timestamp'] = [
            'class' => TimestampBehavior::class,
            'value' => date("Y-m-d H:i:s"),
        ];

        return $behaviors;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['name', 'code', 'phone', 'email', 'city', 'district', 'ward', 'address', 'group_vendor', 'type', 'tax_code', 'company_name', 'current_debt'], 'default', 'value' => null],
            [['group_vendor', 'type'], 'integer'],
            [['current_debt'], 'number'],
            [['name', 'code', 'phone', 'email', 'city', 'district', 'ward', 'address', 'tax_code', 'company_name'], 'string', 'max' => 255]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'name' => 'Name',
            'code' => 'Code',
            'phone' => 'Phone',
            'email' => 'Email',
            'city' => 'City',
            'district' => 'District',
            'ward' => 'Ward',
            'address' => 'Address',
            'group_vendor' => 'Group Vendor',
            'type' => 'Type',
            'tax_code' => 'Tax Code',
            'company_name' => 'Company Name',
            'current_debt' => 'Current Debt',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ]);
    }

    /**
     * @inheritdoc
     * @return VendorQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new VendorQuery(static::class);
    }
}
