<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use yii\behaviors\TimestampBehavior;
use \app\models\WorkScheduleQuery;

/**
 * This is the base-model class for table "work_schedule".
 *
 * @property integer $id
 * @property integer $employee_id
 * @property integer $shift_id
 * @property string $work_date
 * @property integer $repeat_weekly
 * @property string $repeat_days
 * @property string $end_date
 * @property integer $apply_holiday
 * @property integer $copied_from
 * @property integer $status
 * @property string $created_at
 * @property string $updated_at
 */
abstract class WorkSchedule extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'work_schedule';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['timestamp'] = [
            'class' => TimestampBehavior::class,
            'value' => (new \DateTime())->format('Y-m-d H:i:s'),
                        ];
        
    return $behaviors;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['employee_id', 'shift_id', 'work_date', 'repeat_weekly', 'repeat_days', 'end_date', 'apply_holiday', 'copied_from', 'status'], 'default', 'value' => null],
            [['employee_id', 'shift_id', 'repeat_weekly', 'apply_holiday', 'copied_from', 'status'], 'integer'],
            [['work_date', 'end_date'], 'safe'],
            [['repeat_days'], 'string']
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'employee_id' => 'Employee ID',
            'shift_id' => 'Shift ID',
            'work_date' => 'Work Date',
            'repeat_weekly' => 'Repeat Weekly',
            'repeat_days' => 'Repeat Days',
            'end_date' => 'End Date',
            'apply_holiday' => 'Apply Holiday',
            'copied_from' => 'Copied From',
            'status' => 'Status',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ]);
    }

    /**
     * @inheritdoc
     * @return WorkScheduleQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new WorkScheduleQuery(static::class);
    }
}
