<?php

namespace app\modules\v1\admin\user\models\form;

use Yii;
use yii\base\Exception;
use yii\base\InvalidConfigException;
use app\modules\v1\admin\user\models\User;

class UserForm extends User
{
    public $password;
    public $role_input;
    public function rules()
    {
        return array_merge(parent::rules(), [
            [["email", "username"], "required"],
            [["email", "username"], "unique", 'filter' => [
                "!=", "status", self::STATUS_DELETED
            ]],
            ["password", "required", "on" => self::SCENARIO_CREATE],
            ["email", "email"],
            ["status", "default", "value" => self::STATUS_ACTIVE],
            ["role_input", "in", "range" => [
                self::ROLE_USER,
                self::ROLE_MANAGER,
                self::ROLE_ADMIN,
                self::ROLE_APPLICATION
            ]]
        ]);
    }

    /**
     * @throws Exception
     * @throws InvalidConfigException
     */
    public function beforeSave($insert): bool
    {
        if ($this->password) {
            $this->setPassword($this->password);
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * @throws \Exception
     */
    public function afterSave($insert, $changedAttributes)
    {
        if ($this->role_input) {
            $auth = Yii::$app->authManager;
            $auth->revokeAll($this->getId());
            $auth->assign($auth->getRole($this->role_input), $this->getId());
            parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
        }
    }
}