<?php

namespace app\modules\v1;

use yii\base\Module as BaseModule;

class Module extends BaseModule
{
    public function init()
    {
        $this->modules = [
//            "admin" => admin\AdminModule::class,
//            "end-user" => end_user\Module::class,
//            'public' => public\PublicModule::class
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }
}