<?php


namespace app\modules\v1\end_user;


class Module extends \yii\base\Module
{
    public function init()
    {
        $this->modules = [
            "product" => product\Module::class,
            "cart" => cart\Module::class,
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }
}